### ISSUE TITLE
Ver usuarios y promotor del viaje

### ISSUE THREAD

**Issue by damianplz** [damianplz/ShareMyTrip2#1]
**# Sí el usuario está registrado podrá ver
la identidad del promotor del viaje y del resto de participantes
confirmados del viaje.**
• Opción Filtrado1: El usuario podrá filtrar el listado anterior por los campos combinados Origen y
Destino al menos para localizar rápidamente los viajes de su interés. Cada nueva tecla que el usuario
pulse en el campo de búsqueda deberá de regenerar el listado.
• Opción Ordenacion1: El usuario podrá seleccionar el tipo de ordenación para los viajes: origen,
destino, fecha, promotor, etc. Se valorará ordenación combinada de campos.
• Opción Paginación1: El usuario podrá seleccionar el número de filas visualizables.

**Comment by robertofd1995** [comment]
Las opcionales ya estan hechas

**Comment by robertofd1995** [comment]
Hecho
