### ISSUE TITLE
Seguridad

### ISSUE THREAD

**Issue by damianplz** [damianplz/ShareMyTrip2#9]
Deberán tenerse en cuenta los siguientes aspectos de seguridad:
• Emplear la técnica de autentificación/autorización más adecuada a este contexto.
• Se recomienda el uso de un URL inicial diferente para cada rol.
• Es obligatorio utilizar la librería de logging para registrar el funcionamiento interno de la
aplicación.

**Comment by robertofd1995** [comment]
Se va a emplear la técnica de autorización por filtro .

El perfil usuario registrado , funciona correctamente , este perfil podrá acceder a las paginas restricted.

En caso de añadir mas tipos de usuarios , se debera implementar un filtro nuevo por cada usuario.

**Comment by robertofd1995** [comment]
Hecho
